config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :parties

  resources :restaurants

  get 'users/new'

  root              'static_pages#search'
  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'search'  =>  'static_pages#search'
  get 'check_status'  =>  'static_pages#check_status'
  
  get 'search_results'  =>  'static_pages#search'
  get 'staff_home'  =>  'static_pages#staff_home'
  get 'signup'  =>  'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :parties
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get 'cancel_party' => 'parties#cancel_party'
  get 'drop_party' => 'parties#drop_party'
  get 'parties/:id/table_ready' => 'parties#table_ready'
  get 'parties/:id/notify' => 'parties#notify'
  get 'twilio/send_sms' => 'twilio#send_sms'
  get 'twilio/receive_sms' => 'twilio#receive_sms'

  get  'restaurants/:id/estwait' => 'restaurants#estwait'

  post 'api/signup'
  post 'api/signin'
  post 'api/reset_password'

  get 'api/get_waitlist'
  post 'api/add_party'
  get 'api/get_restaurant'
  delete 'api/seat_party'  => 'parties#seat_party'
    
  get 'api/get_token'  
  get 'api/clear_token'

end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :party_status
  before_validation :format_phone

  default_scope -> { order(created_at: :asc) }
  validates :restaurant_id, presence: true
  
  validates :name,  presence: true, length: { maximum: 50 }
  #FUTURE: allow restaurants to set max party size and validate that dynamically
  validates_numericality_of :size,  presence: true, length: { maximum: 50 }, greater_than: 0 
  VALID_PHONE_REGEX = /(1?[ -.]?\(?\d{3}\)?[ -.]?\d{3}[ -.]?\d{4}[ extension\.]*\d{0,5})/i
  validates :phone, length: { maximum: 50 },
                    allow_blank: true,
                    format: { with: VALID_PHONE_REGEX }

  after_initialize :init
  
  def init
    if self.new_record?
      self.party_status_id ||= 1
      self.token ||= random_uniq_token
    end
  end
  
  def format_phone
    self.phone = self.phone.scan(/[0-9]/).join
  end

  # generates a unique token for a party restaurant id + random num between 0 and 999
  def random_uniq_token
    potential_tok = 0
    tries = 0
    loop do 
      tries += 1
      potential_tok = self.restaurant_id * 1000 + SecureRandom.random_number(1000)
      break if Party.where(token: potential_tok, party_status_id: 1).count == 0
      if tries > 100
        raise RuntimeError, "Cannot find unique token for party", caller
      end
    end
    potential_tok
  end

  def status
    return self.party_status.name
  end

  def waiting?
    self.status == "waiting" ? true : false
  end

  def waiting_list_position
    if self.waiting?
      Party.where(restaurant:self.restaurant, party_status_id: 1).where(["created_at <= ?", self.created_at]).count
    else
      0
    end
  end
  
end

app/controllers/parties_controller.rb
include ActionView::Helpers::DateHelper
class PartiesController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :new, :create, :destroy, :edit, :update]
  before_action :correct_user,   only: [:show,  :edit, :update]
  before_action :correct_restaurant_user,   only: [:create]
  
  def index
    @parties = Party.paginate(page: params[:page])
  end
 
  def new
    @party = Party.new
    @restaurant = Restaurant.find_by(id: params[:id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id].to_f)
    @party = @restaurant.parties.build(party_params)
    if @party.save
      flash[:success] = "Party created with token #{@party.token} !"
      redirect_to :controller => "twilio",
        :action => "send_sms",
        :restaurant_id => @party.restaurant_id,
        :phone =>@party.phone,
        :sms_body => "#{@party.name}, Your party token at #{@party.restaurant.name} is: #{@party.token}. Text back #{@party.token} for status."
    else
      flash[:danger] = "Party could NOT be created!"
      render @restaurant
    end
  end
 
  def show
    @party = Party.find(params[:id])
    @restaurant = @party.restaurant
  end
  
  def edit
    @party = Party.find(params[:id])
  end
  
  def update
    @party = Party.find(params[:id])
    if @party.update(party_params)
      redirect_to @party
    else
      render 'edit'
    end
  end
  
  def destroy
    party = Party.find(params[:id])
    party.restaurant.est_wait_time = Party.first.created_at - Time.now 
    party.restaurant.save!
    party.destroy
    redirect_to(:back)
  end
  
  def seat
    party = Party.find(params[:id])
    party.restaurant.est_wait_time = Party.first.created_at - Time.now 
    party.restaurant.save!
    party.update_attributes(party_status: PartyStatus.find_by(name: "seated"))
    redirect_to(:back)
  end
  
  def table_ready
    @party = Party.find(params[:id])
    @party.restaurant.est_wait_time = Party.first.created_at - Time.now 
    @party.restaurant.save!
    # either set flash or append to it, this informational message
    (flash[:notice] ||= "") << " Texting " + @party.phone + "..."

    # let the twilio controller handle the sms
    redirect_to :controller => "twilio", :action => "send_sms", :restaurant_id => @party.restaurant_id,
      :phone =>@party.phone, :sms_body => "#{@party.name}, Your table is ready at #{@party.restaurant.name} (party: #{@party.token})"

    @party.update_attributes(party_status: PartyStatus.find_by(name: "seated"))
  end

  def notify
    @party = Party.find(params[:id])
    # either set flash or append to it, this informational message
    (flash[:notice] ||= "") << " Texting " + @party.phone + "..."

    # let the twilio controller handle the sms
    redirect_to :controller => "twilio", :action => "send_sms", :restaurant_id => @party.restaurant_id,
      :phone =>@party.phone, :sms_body => "#{@party.name}, Your table is coming up at #{@party.restaurant.name} (party: #{@party.token})"
  end

  def cancel
    party = Party.find(params[:id])
    party.restaurant.est_wait_time = Party.first.created_at - Time.now 
    party.restaurant.save!
    party.update_attributes(party_status: PartyStatus.find_by(name: "cancelled"))
    redirect_to(:back)
  end
    
  def drop_down
  end
    
  def cancel_party
  end
  
  private

    def party_params
      params.require(:party).permit(:name, :size, :phone)
    end
    
    def correct_user
      @party = Party.find_by(id: params[:id])
      @restaurant = current_user.restaurants.find_by(id: @party.restaurant_id)
      if @restaurant.nil? 
        flash[:danger] = "Sorry, you are not authorized for this action!"
        redirect_to root_url 
      end
    end
    
    def correct_restaurant_user
      @party = Party.find_by(id: params[:id])
      @restaurant = current_user.restaurants.find_by(id: params[:restaurant_id])
      if @restaurant.nil? 
        flash[:danger] = "Sorry, you are not authorized for this action!"
        redirect_to root_url 
      end
    end
    
    
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
    <%= form_for @party do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :size %>
      <%= f.number_field :size, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>

app/views/parties/_party.html.erb
<% if logged_in?  && party.restaurant.users.include?(current_user) %>
<tr id="party-<%= party.id %>">
  <td class="partyContent"><%= party.token %></td>
  <td class="partyContent"><%= party.name %></td>
  <td class="partyContent"><%= party.size %></td>
  <td class="partyContent"><% if (party.phone.length == 10) %>
                           <%= party.phone.unpack('A3A3A4').join('-') %>
                           <% else %>
                           <%= party.phone.unpack('A1A3A3A*').join('-') %>
                           <% end %></td>
  <td class="timestamp">
    <%= time_ago_in_words(party.created_at) %>
  </td>
  <td class="restaurant"><%= link_to party.restaurant.name, party.restaurant %></td>
  <td><%= link_to 'Edit', edit_party_path(party) %></td>
  <td><%= link_to 'Seat/Delete', id: party.id, controller: "parties", method: :get, action: :table_ready, data: { confirm: 'Are you sure?' } %></td>
  <td><%= link_to 'Notify', id: party.id, controller: "parties", method: :get, action: :notify, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% else %>
<tr id="party-<%= party.id %>">
  <td class="partyContent"><%= party.size %></td>
  <td class="timestamp">
    <%= time_ago_in_words(party.created_at) %>
  </td>
</tr>
<% end %>

app/views/parties/edit.html.erb
<% provide(:title, 'Edit Party') %>
<h1>Edit Party</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<% provide(:title, 'All parties') %>
<h1>All parties</h1>

<%= will_paginate %>
<table class="table">
  <tr class="parties">
  <th>Name</th>
  <th>Size</th>
  <th>Status</th>
  <th>Phone</th>
  <th>Created Time</th>
  <th>Restaurant</th>
  <th>Edit</th>
  <th>Delete</th>
  </tr>
  <%= render @parties %>
</table>

<%= will_paginate %>


<%= link_to 'Add Party', new_party_path %>

app/views/parties/new.html.erb
<% provide(:title, 'Add Party') %>
<h1>Add Party</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/parties/show.html.erb
<% provide(:title, @party.name) %>
<h1>Party <%=  @party.name %></h1>
<div class = "row">
  <aside class = "col-md-4">
    <section class = "user_info">
      <h1>
        <ul class="list-unstyled">
        <li>Name: <%= @party.name %></li>
        <li>Size: <%= @party.size %></li>
        <li>Phone Number: <%= @party.phone %></li>
        <li>Start Time: <%= @party.created_at %></li>
        <li>Seated Time: <%= @party.seated_time %></li>
        <li>Exit Time: <%= @party.exit_time %></li>
        <li>Restaurant: <%= @party.restaurant %></li>
        <li><%= link_to 'Edit', edit_party_path(@party) %></li>
        <li><%= link_to 'Back', parties_path %></li>
        </ul>
      </h1>
    </section>
  </aside>
</div>