config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :parties

  resources :restaurants

  get 'users/new'

  root              'static_pages#search'
  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'search'  =>  'static_pages#search'
  get 'check_status'  =>  'static_pages#check_status'
  
  get 'search_results'  =>  'static_pages#search'
  get 'staff_home'  =>  'static_pages#staff_home'
  get 'signup'  =>  'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :parties
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get 'cancel_party' => 'parties#cancel_party'
  get 'drop_party' => 'parties#drop_party'
  get 'parties/:id/table_ready' => 'parties#table_ready'
  get 'parties/:id/notify' => 'parties#notify'
  get 'twilio/send_sms' => 'twilio#send_sms'
  get 'twilio/receive_sms' => 'twilio#receive_sms'

  get  'restaurants/:id/estwait' => 'restaurants#estwait'

  post 'api/signup'
  post 'api/signin'
  post 'api/reset_password'

  get 'api/get_waitlist'
  post 'api/add_party'
  get 'api/get_restaurant'
  delete 'api/seat_party'  => 'parties#seat_party'
    
  get 'api/get_token'  
  get 'api/clear_token'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @restaurant = current_user.restaurants.build if logged_in?
  end

  def search
    if params[:search]
      @restaurants = Restaurant.search(params[:search]).paginate(page: params[:page])
    else
      @restaurants = Restaurant.paginate(page: params[:page])
    end
  end
  
  

  def check_status
    if params[:search_party_name] && params[:search_party_phone] && params[:search_party_id]
      @party = Party.find_by(name: params[:search_party_name], phone: params[:search_party_phone].scan(/[0-9]/).join, id: params[:search_party_id])      
      @party_placement = (@party ? @party.waiting_list_position : 0)
    else
      
    end
  end
  
  def staff_home
    @restaurant = current_user.restaurants.first
  end
  
  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>

app/views/static_pages/check_status.html.erb
<% provide(:title, 'Check Wait Status') %>
<h1>Check Wait Status</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">   
    <%= form_tag(check_status_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search_party_name, params[:search_party_name], placeholder: "Name*", :required => true, class: 'form-control'%>
    <%= text_field_tag :search_party_phone, params[:search_party_phone], placeholder: "Phone*", :required => true, class: 'form-control'%>
    <%= text_field_tag :search_party_id, params[:search_party_id], placeholder: "ID*", :required => true, class: 'form-control'%>
    <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>



<p id="notice"><%= notice %></p>

<% if @party && (@party_placement > 0) %>
    <h1>You are party #<%= @party_placement %> at <%= link_to @party.restaurant.name, @party.restaurant %> </h1>
    <h1>Estimated Time Left = 
    <%if (Time.now - @party.created_at) > @party.restaurant.est_wait_time  %>
        5 mins </h1>
    <%else %>
        <%= ((@party.restaurant.est_wait_time - (Time.now - @party.created_at)) / 60).round %> mins </h1>
    <%end%>
<% else %>
    <h1>There is no party with that name, phone, and id on the waiting list. </h1>

<% end %>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://www.railstutorial.org/#help">Rails Tutorial help
      section</a>.
      To get help on this sample app, see the
      <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
      Tutorial</em> book</a>.
    </p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
    </aside>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to <%= "#{$site_name}" %></h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
<% end %>

app/views/static_pages/search.html.erb
<div class = "seatpop_image">
  <div class="center site-header">
    <%= "#{$site_name}" %>
  </div>
  <div class = "seach_box">
    <%= form_tag(search_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Restaurants", class: 'form-control'%>
    <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>


<p id="notice"><%= notice %></p>
<h1>Restaurants</h1>


<%= will_paginate @restaurants%>
  <%= render @restaurants %>

<%= will_paginate @restaurants%>