config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :parties

  resources :restaurants

  get 'users/new'

  root              'static_pages#search'
  get 'help'    =>  'static_pages#help'
  get 'about'   =>  'static_pages#about'
  get 'contact' =>  'static_pages#contact'
  get 'search'  =>  'static_pages#search'
  get 'check_status'  =>  'static_pages#check_status'
  
  get 'search_results'  =>  'static_pages#search'
  get 'staff_home'  =>  'static_pages#staff_home'
  get 'signup'  =>  'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :parties
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  
  get 'cancel_party' => 'parties#cancel_party'
  get 'drop_party' => 'parties#drop_party'
  get 'parties/:id/table_ready' => 'parties#table_ready'
  get 'parties/:id/notify' => 'parties#notify'
  get 'twilio/send_sms' => 'twilio#send_sms'
  get 'twilio/receive_sms' => 'twilio#receive_sms'

  get  'restaurants/:id/estwait' => 'restaurants#estwait'

  post 'api/signup'
  post 'api/signin'
  post 'api/reset_password'

  get 'api/get_waitlist'
  post 'api/add_party'
  get 'api/get_restaurant'
  delete 'api/seat_party'  => 'parties#seat_party'
    
  get 'api/get_token'  
  get 'api/clear_token'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :parties, dependent: :destroy
  has_many :restaurants_users
  has_many :users, :through => :restaurants_users, :source => :user
  mount_uploader :picture, PictureUploader
  validate  :picture_size
  
  def waitlist 
    Party.where("restaurant_id = ? AND party_status_id = 1", id)
  end
  
  def seatlist 
    Party.where("restaurant_id = ? AND party_status_id = 2", id)
  end

  def exitlist 
    Party.where("restaurant_id = ? AND party_status_id = 3", id)
  end

  def self.search(query)
    where("lower(name) like ?", "%#{query.downcase}%") 
  end


  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 15.megabytes
        errors.add(:picture, "should be less than 15MB")
      end
    end
end

app/controllers/restaurants_controller.rb
require 'action_view'
include ActionView::Helpers::DateHelper

class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :estwait]
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  before_action :admin_user,     only: :destroy
  
  
 # def index
  #  if params[:search]
   #   @restaurants = Restaurant.search(params[:search]).order("created_at DESC")
    #else
     # @restaurants = Restaurant.order("created_at DESC")
    #end
  #end
    
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.users.append(current_user)
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully created.' }
        format.json { redirect_to restaurants_url, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
        
      end
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @party = @restaurant.parties.build if logged_in?
    @waitlist_items = @restaurant.waitlist.paginate(page: params[:page])
    @seatlist_items = @restaurant.seatlist.paginate(page: params[:page])
  end

  def edit

  end

  def update
   respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully updated.' }
        format.json { render :index, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @restaurants = Restaurant.paginate(page: params[:page])
  end


  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def estwait
    if @restaurant.est_wait_time 
        ret_data = {waittimestr: "#{distance_of_time_in_words(@restaurant.est_wait_time)}"}
    else
        ret_data = {waittimestr: "No wait!"}
    end

    ret_data[:waitlistlen] = @restaurant.waitlist.length.to_s + " waiting"

    logger.debug "estwait ret_data: #{ret_data.to_json}"
    respond_to do |format|
      format.html { render html: ret_data[:waittimestr] }
      format.json { render json: ret_data.to_json }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :picture)
    end
    
    def correct_user
      @restaurant = current_user.restaurants.find_by(id: params[:id])
      redirect_to root_url if @restaurant.nil?
    end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, html: { multipart: true }) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name, class: 'form-control'%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit :submit, class: "btn btn-primary"  %>
  </div>
<% end %>


<script type="text/javascript">
  $('#restaurant_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 15) {
      alert('Maximum file size is 15MB. Please choose a smaller file.');
    }
  });
</script>

app/views/restaurants/_party.html.erb
<li id="party-<%= party.id %>">
  <span class="restaurant"><%= link_to party.restaurant.name, party.restaurant %></span>
  <span class="partyContent"><%= party.name %></span>
  <span class="partyContent"><%= party.size %></span>
  <span class="partyContent"><%= party.phone %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(party.created_at) %> ago.
  </span>
</li>

app/views/restaurants/_restaurant.html.erb
<div class="box">

  <span class="restaurant-image"><%= link_to image_tag(restaurant.picture.small.url, width: "200", class: "img-thumbnail"), restaurant if restaurant.picture? %></span>
  <span class="restaurant-name"><%= restaurant.name %></span>  
  <span class="restaurant-waittime" id="restaurant-waittime<%= restaurant.id %>"></span>
  <span class="restaurant-waitlist-len" id="restaurant-waitlist-len<%= restaurant.id %>"></span>

  <% if logged_in? && restaurant.users.include?(current_user) %>
    <span><%= restaurant.description %></span>
  <% end %>
</div>

<script>
$(document).ready(function(){
  var $estwait = $('#restaurant-waittime<%= restaurant.id %>');
  var $waitlistlen = $('#restaurant-waitlist-len<%= restaurant.id %>');

  setInterval(function(){
    $.ajax({
      type: "GET",
      url: "/restaurants/<%= restaurant.id %>/estwait.json",
      dataType: "json",
      success: function(response) {
        console.log("success: response: " + response.waittimestr);
        console.log("success: response: " + response.waitlistlen);
        if ($estwait.length > 0) {
          $estwait.first().text(response.waittimestr);          
        }
        if ($waitlistlen.length > 0) {
          $waitlistlen.first().text(response.waitlistlen);          
        } 
      }
    });

  }, 2000);
});
</script>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'List', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<div>
<%= link_to 'Add New Restaurant', new_restaurant_path, class: "btn btn-primary"  %>
</div>
<div>
<%= will_paginate %>
  <%= render @restaurants %>
<%= will_paginate %>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'List', restaurants_path %>

app/views/restaurants/show.html.erb
<% provide(:title, @restaurant.name) %>
<% provide(:restaurant_id, params[:id]) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @restaurant.name %>
      </h1>
      
    </section>
<% if logged_in?  && @restaurant.users.include?(current_user) %>

    
    <span><%= link_to 'Edit', edit_restaurant_path(@restaurant) %></span>
    <span><%= link_to 'Destroy', @restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    <div class="row">
      <section class="party_form">
        <%= render 'shared/party_form' %>
      </section>
    </div>
      
    <%= image_tag(@restaurant.picture.small.url, width: "300") if @restaurant.picture? %>
  </aside>
  <div class="col-md-8">
    <% if @restaurant.parties.any? %>
      <h3>Waitlist (<%= @restaurant.waitlist.count %>)</h3>
      
      <%= render 'shared/waitlist' %>
    <% end %>
  </div>
  <div class="col-md-8">
    <% if @restaurant.parties.any? %>
      <h3>Seated Parties (<%= @restaurant.seatlist.count %>)</h3>
      
      <%= render 'shared/seatlist' %>
    <% end %>
  </div>
</div>
<%else %>
   <%= image_tag(@restaurant.picture.small.url, width: "300") if @restaurant.picture? %>
  </aside>
  <div class="col-md-8">
    <% if @restaurant.parties.any? %>
      <h3>Waitlist</h3>
      
      <%= render 'shared/waitlist' %>
    <% end %>
  </div>
    <% end %>
    
    